#!/usr/bin/env zsh

# Empty the on the main HDD.
sudo rm -rfv ~/.Trash/*

# Also, clear Apple’s System Logs to improve shell startup speed.
sudo rm -rfv /private/var/log/asl/*.asl

# Finally, clear download history from quarantine. https://mths.be/bum
sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
